### ISSUE TITLE
Update Nord in themes.json

### ISSUE THREAD

**Issue by kyan001** [atomcorp/themes#45]
Mensioned at #44 , the Nord scheme is from https://github.com/mbadolato/iTerm2-Color-Schemes.
I checked https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/windowsterminal/nord.json, it has the correct scheme for Windows Terminal, please update Nord scheme in themes.json accordingly.

**Comment by atomcorp** [comment]
Heya, the themes.json in this repo doesn't actually do anything. I've removed it now because it was confusing people.

If you checkout the endpoint I use for the site https://www.atomcorp.dev/api/v1/themes and compare it with the iTerm2 page you listed, they should be the same. 

Cheers!
