### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by jos3s** [atomcorp/themes#7]
Could you add a category to README for everyone who contributed to this repository?

**Comment by atomcorp** [comment]
Yeah, I'l add something like this, sure! Thanks

**Comment by jos3s** [comment]
Here the PR with this suggestion https://github.com/atomcorp/themes/pull/10

**Comment by atomcorp** [comment]
Cheers, I'll accept the pull request. 

I would like to automate this though in future, probably by attaching the information to the themes objects. Then it can be used on the site or generated into a markdown file for the repo.

**Comment by jos3s** [comment]
Thank you, I hope you can do this
