### ISSUE TITLE
Question: Is there a static link to the JSON file?

### ISSUE THREAD

**Issue by potatoqualitee** [atomcorp/themes#85]
Currently, I'm having to spin up playwright to get that json file for a CI/CD project I'm doing. Any chance there's a direct link to the (surprisingly useful ;)) JSON file?

**Comment by atomcorp** [comment]
Hello! Can't you use https://www.atomcorp.dev/api/v1/themes? Not sure I follow otherwise. I might change the endpoint at some point too, just fyi...

**Comment by potatoqualitee** [comment]
Oh wow! I did not know about this, thank you!
