### ISSUE TITLE
[Bug] Cannot see - in powershell.

### ISSUE THREAD

**Issue by 378978764** [atomcorp/themes#9]
"colorScheme": "Builtin Solarized Dark"
The apperance looks well, but when I type `-`, it becomes transparent.

**Comment by 378978764** [comment]
![Snipaste_2020-05-26_14-36-10](https://user-images.githubusercontent.com/13643746/82868159-bf183b80-9f5e-11ea-891d-44d3793fd2da.png)

**Comment by atomcorp** [comment]
Hey!

I just grab that themes from github.com/mbadolato/iTerm2-Color-Schemes, so I wouldn't be able to change anything, they would. That said PowerShell seems to add some of it's own syntax highlighting, I don't use it so I'm not sure why/how - but I suspect it would need to be changed in PowerShell. Maybe this will help, or set you on the right path at least: https://4sysops.com/wiki/change-powershell-console-syntax-highlighting-colors-of-psreadline/

**Comment by 378978764** [comment]
> Hey!
> 
> I just grab that themes from github.com/mbadolato/iTerm2-Color-Schemes, so I wouldn't be able to change anything, they would. That said PowerShell seems to add some of it's own syntax highlighting, I don't use it so I'm not sure why/how - but I suspect it would need to be changed in PowerShell. Maybe this will help, or set you on the right path at least: https://4sysops.com/wiki/change-powershell-console-syntax-highlighting-colors-of-psreadline/

Thanks for your reply. Using `Solarized Dark - Patched` solved this.
